# Generated by Django 4.2.1 on 2023-05-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompressedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original", models.ImageField(upload_to="originals/")),
                ("compressed", models.ImageField(blank=True, upload_to="compressed/")),
            ],
        ),
    ]
