# Generated by Django 4.2.1 on 2023-05-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("svd_demo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DenoisedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original", models.ImageField(upload_to="originals/")),
                ("denoised", models.ImageField(blank=True, upload_to="denoised/")),
            ],
        ),
    ]
